### ISSUE TITLE
Bundle state

### ISSUE THREAD

**Issue by RomainSanchez** [shapecode/doctrine-session-handler-bundle#1]
Hi there, we are going to use this bundle in our projects and we where wondering if it was still maintained.If it is not please let us know if you would be ok to transfer ownership or should we just fork.

**Comment by nicklog** [comment]
Yeah, of cource, but a the moment there is no improvements to do.
If you have suggestions, feel free to make a PR.

Thanks ;)

**Comment by RomainSanchez** [comment]
Ok.good to know.thanks
