### ISSUE TITLE
Using Session as a table name is bad practice

### ISSUE THREAD

**Issue by MicWit** [shapecode/doctrine-session-handler-bundle#2]
When setting up the doctrine session handler it fails on Oracle because the word session is an SQL (and Oracle) reserved word. This will potentially cause issues down the track. (see https://docs.oracle.com/database/121/SQLRF/ap_keywd001.htm#SQLRF55621 and https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words).

My suggestion is to change the table name to something like doctrine_session or symfony_session in order to get around this problem.

Note that using "Session" (with quotations) is a work around but not a good one and will potentially cause problems as well, there is no need to do this as a different table name will work way better in the long run.

**Comment by nicklog** [comment]
i will check it

**Comment by nicklog** [comment]
take a look at the 2.0 dev release.

**Comment by MicWit** [comment]
Cool, so there are no config changes required, just the new code? Note that I submitted a patch for the readme with just a few extra bits of info to make it easier for beginners.

Im in Australia, so when I get to work tomorrow I will throw the 2.0 code into the project to test it. Am I able to do this from composer (I'm new to composer installs) or is that only available for stable versions?

**Comment by nicklog** [comment]
yeah, just change the required version to "2.0@dev".

i didnt see any patch?!

**Comment by MicWit** [comment]
I'm not sure what happened there (not used to git/github outside of an organisation). I thought I forked Dev but seems to have attached to another patch somehow. I just created a pull request. Can u see that?

**Comment by MicWit** [comment]
"shapecode/doctrine-session-handler-bundle": "2.0@dev" brings back the message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package shapecode/doctrine-session-handler-bundle 2.0@dev exists as shapecode/doctrine-session-handler-bundle[1.0.0, 1.1.0, 1.1.1, dev-develop, dev-master, dev-release/1.0, 1.0.x-dev, dev-release/1.1, 1.1.x-dev, dev-release/2.0, 2.0.x-dev] but these are rejected by your constraint.
```

**Comment by MicWit** [comment]
"shapecode/doctrine-session-handler-bundle": "dev-release/2.0" seems to install fine.

**Comment by MicWit** [comment]
I have been testing, so far so good. I found a bug in Symfony though and reported it at: https://github.com/symfony/symfony/issues/21641 I was trying to test the clearing of expired sessions and found that Symfony (and PHP) do it randomly with a probability set in php.ini. It seems Symfony overwrites 1 of the 2 variables that probability is derived from making it impossible to test expiry of sessions.

**Comment by nicklog** [comment]
you do not allow dev states. because of this you couldnt install 2.0 the "normal" way. but i found a mistake by myself. it should be "~2.0@dev".

**Comment by MicWit** [comment]
This all now appears to be working fine, I have run a bunch of tests on a fresh Symfony project. Any ETA on when this could be put to master and a 2.0 release done?

**Comment by nicklog** [comment]
i can do it just right now.

**Comment by MicWit** [comment]
Im not seeing release 2 as being in master, should it be?

**Comment by nicklog** [comment]
it is in master, but havn't to be. See here: [https://packagist.org/packages/shapecode/doctrine-session-handler-bundle#2.0.0](https://packagist.org/packages/shapecode/doctrine-session-handler-bundle#2.0.0)

dont set the require statement in your composer.json to "dev-master". use "~2.0".

**Comment by MicWit** [comment]
Updated docs and all is running well, closing issue.
